apiVersion: v1
kind: Pod 
metadata:
  name: web
  labels:
    key: app
spec:
  containers:
  - name: web 
    image: web:1.0.0
    imagePullPolicy: Never
    volumeMounts:
      - name: app
        mountPath: /usr/share/nginx/html
  initContainers:
  - name: init-index
    image: busybox:1.36
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app
  volumes:
  - name: app    
    emptyDir: {}
